# Generated by Django 6.0.2 on 2026-03-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='horas_servicio',
        ),
    ]
