# Generated by Django 6.0.2 on 2026-03-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_remove_alumno_horas_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='horas_acumuladas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado')], default='Activo', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prestamos.alumno')),
            ],
        ),
    ]
