# Generated by Django 6.0.2 on 2026-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_prestamo_horas_acumuladas_alter_prestamo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='horas_acumuladas',
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='horas_acumuladas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('No Entregado', 'No Entregado')], default='Pendiente', max_length=20),
        ),
    ]
