# Generated by Django 6.0.2 on 2026-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_remove_prestamo_horas_acumuladas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
