# Generated by Django 6.0.2 on 2026-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_prestamo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
