# Generated by Django 6.0.2 on 2026-05-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_prestamo_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='disponibles',
        ),
        migrations.RemoveField(
            model_name='material',
            name='total_fisico',
        ),
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=dict, help_text='Ej: {"talla": "M", "color": "Rojo"}'),
        ),
        migrations.AddField(
            model_name='material',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo por pieza', max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='estado_fisico',
            field=models.CharField(choices=[('Bueno', 'Buen Estado'), ('Medio', 'Estado Medio'), ('Malo', 'Mal Estado')], default='Bueno', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_llegada',
            field=models.DateField(blank=True, help_text='Fecha en que dirección asignó el material', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
