# Generated by Django 6.0.2 on 2026-05-27 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_remove_material_disponibles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('datos_faciales', models.JSONField(blank=True, help_text='Vectores matemáticos del rostro', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar cuando termine su servicio')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.prestadorservicio')),
            ],
        ),
    ]
