# Generated by Django 6.0.2 on 2026-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_prestadorservicio_asistenciaservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='material',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
