# Generated by Django 6.0.5 on 2026-05-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_alter_material_caracteristicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciaservicio',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='asistenciaservicio',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='asistenciaservicio',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Entrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistenciaservicio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestadorservicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
